version: '3.8'
services:

  dev-db:
    container_name: pg_container
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=viblo

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ROOTNAME
      MINIO_ROOT_PASSWORD: CHANGEME123
    volumes:
      - ~/minio/data:/data
    command: server /data --console-address ":9001"

#   nestjs_server:
#     build: ./
#     container_name: nestjs_server
#     ports:
#       - 8000:3000
#     environment:
#       - JWT_KEY=${JWT_KEY}
#       - DATABASE_HOST=dev-db
#       - DATABASE_PORT=5432
#       - DATABASE_USER=postgres
#       - DATABASE_PASSWORD=1234
#       - DATABASE_NAME=viblo
#     depends_on:
#       - dev-db
#     networks:
#       - shared-network
#     restart: unless-stopped
# networks:
#   shared-network:
