version: '3.8'
services:

  dev-db:
    container_name: ${POSTGES_CONTAINER_NAME}
    image: postgres:latest
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

    
  test-db:
    container_name: ${POSTGES_TEST_CONTAINER_NAME}
    image: postgres:latest
    restart: always
    ports:
      - ${POSTGRES_TEST_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_TEST_USER}
      - POSTGRES_PASSWORD={POSTGRES_TEST_PASSWORD}
      - POSTGRES_DB=${POSTGRES_TEST_DB}


  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - ~/minio/data:/data
    command: server /data --console-address ":9001"
    # app:
    #     build:
    #       context: ./nestjs-server
    #       dockerfile: Dockerfile
    #     container_name: nest-docker-postgres
    #     environment:
    #       - PORT=${PORT}
    #     ports:
    #       - '3000:3000'
    #     depends_on:
    #       - db
    #     volumes:
    #       - ./src:/app/src

    # networks:
    #   shared-network:
volumes:
  cloudbeaver:
#  api.viblo.local
# viblo.local
# https
# /etc/hosts : DNS