version: '3.8'
services:
  dev-db:
    container_name: ${POSTGES_CONTAINER_NAME}
    image: postgres:latest
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  test-db:
    container_name: ${POSTGES_TEST_CONTAINER_NAME}
    image: postgres:latest
    restart: always
    ports:
      - ${POSTGRES_TEST_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_TEST_USER}
      - POSTGRES_PASSWORD={POSTGRES_TEST_PASSWORD}
      - POSTGRES_DB=${POSTGRES_TEST_DB}
  nestjs-server:
    build:
      context: ./nestjs-server  # Chỉ định thư mục chứa Dockerfile
      dockerfile: Dockerfile     # Tên file Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - dev-db
    environment:
      DATABASE_HOST: dev-db
      DATABASE_PORT: ${POSTGRES_PORT}        # Port của PostgreSQL
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_NAME: ${POSTGRES_DB}
      DATABASE_USER: ${POSTGRES_USER}
    volumes:
      - ./nestjs-server:/app            # Gắn mã nguồn của bạn vào container
      - /app/node_modules               # Đảm bảo node_modules không bị ghi đè
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'      # Giới hạn CPU cho container
          memory: 512M     # Giới hạn bộ nhớ cho container
        reservations:
          cpus: '0.5'      # Đảm bảo có sẵn tài nguyên CPU
          memory: 512M     # Đảm bảo có sẵn bộ nhớ
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - ~/minio/data:/data
    command: server /data --console-address ":9001"

  react-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules   
    environment:
      - PORT=3000
    restart: always
volumes:
  cloudbeaver:


#  api.viblo.local
# viblo.local
# https
# /etc/hosts : DNS