const actionTypes = Object.freeze({
  // REGISTER
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE",
  // LOGIN
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAILURE: "USER_LOGIN_FAILURE",

  // LOGOUT
  USER_LOGOUT_SUCCESS: "USER_LOGOUT_SUCCESS",
  USER_LOGOUT_FAILURE: "USER_LOGOUT_FAILURE",

  GET_ALL_USER: "GET_ALL_USER",

  // TAG
  GET_TAGS_SUCCESS: "GET_TAG_SUCCESS",
  GET_TAGS_FAILURE: "GET_TAG_FAILURE",
});
export default actionTypes;
