const actionTypes = Object.freeze({
  // REGISTER
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE",
  // LOGIN
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAILURE: "USER_LOGIN_FAILURE",

  // LOGOUT
  USER_LOGOUT_SUCCESS: "USER_LOGOUT_SUCCESS",
  USER_LOGOUT_FAILURE: "USER_LOGOUT_FAILURE",

  //USER
  GET_ALL_USER: "GET_ALL_USER",
  UPDATE_USER_AVATAR: "UPDATE_USER_AVATAR",
  GET_TOP_AUTHOR_SUCCESS: "GET_TOP_AUTHOR_SUCCESS",
  GET_TOP_AUTHOR_FAILED: "GET_TOP_AUTHOR_FAILED",

  // TAG
  GET_TAGS_SUCCESS: "GET_TAG_SUCCESS",
  GET_TAGS_FAILURE: "GET_TAG_FAILURE",

  // POST
  GET_POST_ID_SUCCESS: "GET_POST_ID_SUCCESS",
  GET_POST_ID_FAILED: "GET_POST_ID_FAILED",
  GET_POST_PAGINATION_SUCCESS: "GET_POST_PAGINATION_SUCCESS",
  GET_POST_PAGINATION_FAILED: "GET_POST_PAGINATION_FAILED",
  GET_RELATED_POST_SUCCESS: "GET_RELATED_POST_SUCCESS",
  GET_RELATED_POST_FAILED: "GET_RELATED_POST_FAILED",

  //COMMENT
  GET_COMMENT_BY_POST_ID_SUCCESS: "GET_COMMENT_BY_POST_ID_SUCCESS",
  GET_COMMENT_BY_POST_ID_FAILED: "GET_COMMENT_BY_POST_ID_FAILED",

  //STATISTIC
  GET_TAG_STATISTIC_SUCCESS: "GET_TAG_STATISTIC_SUCCESS",
  GET_TAG_STATISTIC_FAILED: "GET_TAG_STATISTIC_FAILED",
  GET_COMMON_STATISTIC_SUCCESS: "GET_COMMON_STATISTIC_SUCCESS",
  GET_COMMON_STATISTIC_FAILED: "GET_COMMON_STATISTIC_FAILED",
});
export default actionTypes;
